### ISSUE TITLE
bug: wasm compilation error deriving from pkarr -> getrandom

### ISSUE THREAD

**Issue by SHAcollision** [pubky/pubky-core#68]
Currently `pubky-app-specs` wasm cannot build using `pkarr=v3.1.1` and `pubky-common=v0.3.0` 

```
   Compiling serde-wasm-bindgen v0.6.5
error: The wasm32-unknown-unknown targets are not supported by default; you may need to enable the "wasm_js" configuration flag. Note that enabling the `wasm_js` feature flag alone is insufficient. For more information see: https://docs.rs/getrandom/#webassembly-support
   --> /home/crypt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.3.1/src/backends.rs:159:9
    |
159 | /         compile_error!(
160 | |             "The wasm32-unknown-unknown targets are not supported by default; \
161 | |             you may need to enable the \"wasm_js\" configuration flag. Note \
162 | |             that enabling the `wasm_js` feature flag alone is insufficient. \
163 | |             For more information see: \
164 | |             https://docs.rs/getrandom/#webassembly-support"
165 | |         );
    | |_________^
```

It seems this issue might have already be detected and fixed in `pkarr` dependency https://github.com/pubky/pkarr/pull/116

There is no pkarr v3.1.2 release, but it seems the way to go is to test whether using latest `pkarr` in `pubky-core` and use both in `pubky-app-specs` fixes the compilation issues. Must be updated in both to avoid having 2 different `pkarr` versions in `pubky-app-wasm` as it also depends on `pubky-common`.

**Comment by SHAcollision** [comment]
We have been able to remove `pubky-common` as a dependency of `pubky-app-specs`. Therefore, there is no 2 different pkarr versions any more and we could directly test using latest pkarr from `main` :
```toml
pkarr = { git = "https://github.com/pubky/pkarr", branch = "main", package = "pkarr", default-features = false, features = [
    "keys",
] }
```
The wasm now builds successfuly 🚀  Ty @Nuhvi for https://github.com/pubky/pkarr/pull/116

**Comment by SHAcollision** [comment]
Solved by merging https://github.com/pubky/pubky-core/pull/69
